// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiBoardsById, deleteApiPhasesById, deleteApiPhaseTransitionsById, deleteApiTasksById, get, getApiBoards, getApiPhases, getApiPhaseTransitions, getApiTasks, getBoard, getPhase, getTask, getTransition, type Options, postApiBoards, postApiPhases, postApiPhaseTransitions, postApiTasks, putApiBoardsById, putApiPhasesById, putApiPhaseTransitionsById, putApiTasksById } from '../sdk.gen';
import type { DeleteApiBoardsByIdData, DeleteApiPhasesByIdData, DeleteApiPhaseTransitionsByIdData, DeleteApiTasksByIdData, GetApiBoardsData, GetApiBoardsResponse, GetApiPhasesData, GetApiPhasesResponse, GetApiPhaseTransitionsData, GetApiPhaseTransitionsResponse, GetApiTasksData, GetApiTasksResponse, GetBoardData, GetBoardResponse, GetData, GetPhaseData, GetPhaseResponse, GetResponse, GetTaskData, GetTaskResponse, GetTransitionData, GetTransitionResponse, PostApiBoardsData, PostApiBoardsResponse, PostApiPhasesData, PostApiPhasesResponse, PostApiPhaseTransitionsData, PostApiPhaseTransitionsResponse, PostApiTasksData, PostApiTasksResponse, PutApiBoardsByIdData, PutApiBoardsByIdResponse, PutApiPhasesByIdData, PutApiPhasesByIdResponse, PutApiPhaseTransitionsByIdData, PutApiPhaseTransitionsByIdResponse, PutApiTasksByIdData, PutApiTasksByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiBoardsQueryKey = (options?: Options<GetApiBoardsData>) => createQueryKey('getApiBoards', options);

export const getApiBoardsOptions = (options?: Options<GetApiBoardsData>) => queryOptions<GetApiBoardsResponse, DefaultError, GetApiBoardsResponse, ReturnType<typeof getApiBoardsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBoards({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBoardsQueryKey(options)
});

export const postApiBoardsMutation = (options?: Partial<Options<PostApiBoardsData>>): UseMutationOptions<PostApiBoardsResponse, DefaultError, Options<PostApiBoardsData>> => {
    const mutationOptions: UseMutationOptions<PostApiBoardsResponse, DefaultError, Options<PostApiBoardsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiBoards({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiBoardsByIdMutation = (options?: Partial<Options<DeleteApiBoardsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiBoardsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiBoardsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiBoardsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBoardQueryKey = (options: Options<GetBoardData>) => createQueryKey('getBoard', options);

export const getBoardOptions = (options: Options<GetBoardData>) => queryOptions<GetBoardResponse, DefaultError, GetBoardResponse, ReturnType<typeof getBoardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBoard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardQueryKey(options)
});

export const putApiBoardsByIdMutation = (options?: Partial<Options<PutApiBoardsByIdData>>): UseMutationOptions<PutApiBoardsByIdResponse, DefaultError, Options<PutApiBoardsByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiBoardsByIdResponse, DefaultError, Options<PutApiBoardsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiBoardsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getQueryKey = (options?: Options<GetData>) => createQueryKey('get', options);

export const getOptions = (options?: Options<GetData>) => queryOptions<GetResponse, DefaultError, GetResponse, ReturnType<typeof getQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await get({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQueryKey(options)
});

export const getApiPhasesQueryKey = (options?: Options<GetApiPhasesData>) => createQueryKey('getApiPhases', options);

export const getApiPhasesOptions = (options?: Options<GetApiPhasesData>) => queryOptions<GetApiPhasesResponse, DefaultError, GetApiPhasesResponse, ReturnType<typeof getApiPhasesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPhases({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPhasesQueryKey(options)
});

export const postApiPhasesMutation = (options?: Partial<Options<PostApiPhasesData>>): UseMutationOptions<PostApiPhasesResponse, DefaultError, Options<PostApiPhasesData>> => {
    const mutationOptions: UseMutationOptions<PostApiPhasesResponse, DefaultError, Options<PostApiPhasesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPhases({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiPhasesByIdMutation = (options?: Partial<Options<DeleteApiPhasesByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiPhasesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiPhasesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiPhasesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPhaseQueryKey = (options: Options<GetPhaseData>) => createQueryKey('getPhase', options);

export const getPhaseOptions = (options: Options<GetPhaseData>) => queryOptions<GetPhaseResponse, DefaultError, GetPhaseResponse, ReturnType<typeof getPhaseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPhase({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPhaseQueryKey(options)
});

export const putApiPhasesByIdMutation = (options?: Partial<Options<PutApiPhasesByIdData>>): UseMutationOptions<PutApiPhasesByIdResponse, DefaultError, Options<PutApiPhasesByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiPhasesByIdResponse, DefaultError, Options<PutApiPhasesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiPhasesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiPhaseTransitionsQueryKey = (options?: Options<GetApiPhaseTransitionsData>) => createQueryKey('getApiPhaseTransitions', options);

export const getApiPhaseTransitionsOptions = (options?: Options<GetApiPhaseTransitionsData>) => queryOptions<GetApiPhaseTransitionsResponse, DefaultError, GetApiPhaseTransitionsResponse, ReturnType<typeof getApiPhaseTransitionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPhaseTransitions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPhaseTransitionsQueryKey(options)
});

export const postApiPhaseTransitionsMutation = (options?: Partial<Options<PostApiPhaseTransitionsData>>): UseMutationOptions<PostApiPhaseTransitionsResponse, DefaultError, Options<PostApiPhaseTransitionsData>> => {
    const mutationOptions: UseMutationOptions<PostApiPhaseTransitionsResponse, DefaultError, Options<PostApiPhaseTransitionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPhaseTransitions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiPhaseTransitionsByIdMutation = (options?: Partial<Options<DeleteApiPhaseTransitionsByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiPhaseTransitionsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiPhaseTransitionsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiPhaseTransitionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTransitionQueryKey = (options: Options<GetTransitionData>) => createQueryKey('getTransition', options);

export const getTransitionOptions = (options: Options<GetTransitionData>) => queryOptions<GetTransitionResponse, DefaultError, GetTransitionResponse, ReturnType<typeof getTransitionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTransition({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransitionQueryKey(options)
});

export const putApiPhaseTransitionsByIdMutation = (options?: Partial<Options<PutApiPhaseTransitionsByIdData>>): UseMutationOptions<PutApiPhaseTransitionsByIdResponse, DefaultError, Options<PutApiPhaseTransitionsByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiPhaseTransitionsByIdResponse, DefaultError, Options<PutApiPhaseTransitionsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiPhaseTransitionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTasksQueryKey = (options?: Options<GetApiTasksData>) => createQueryKey('getApiTasks', options);

export const getApiTasksOptions = (options?: Options<GetApiTasksData>) => queryOptions<GetApiTasksResponse, DefaultError, GetApiTasksResponse, ReturnType<typeof getApiTasksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTasks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTasksQueryKey(options)
});

export const postApiTasksMutation = (options?: Partial<Options<PostApiTasksData>>): UseMutationOptions<PostApiTasksResponse, DefaultError, Options<PostApiTasksData>> => {
    const mutationOptions: UseMutationOptions<PostApiTasksResponse, DefaultError, Options<PostApiTasksData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTasks({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiTasksByIdMutation = (options?: Partial<Options<DeleteApiTasksByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiTasksByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiTasksByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiTasksById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTaskQueryKey = (options: Options<GetTaskData>) => createQueryKey('getTask', options);

export const getTaskOptions = (options: Options<GetTaskData>) => queryOptions<GetTaskResponse, DefaultError, GetTaskResponse, ReturnType<typeof getTaskQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTask({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTaskQueryKey(options)
});

export const putApiTasksByIdMutation = (options?: Partial<Options<PutApiTasksByIdData>>): UseMutationOptions<PutApiTasksByIdResponse, DefaultError, Options<PutApiTasksByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiTasksByIdResponse, DefaultError, Options<PutApiTasksByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiTasksById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
