// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiBoardsByIdData, DeleteApiBoardsByIdResponses, DeleteApiPhasesByIdData, DeleteApiPhasesByIdResponses, DeleteApiPhaseTransitionsByIdData, DeleteApiPhaseTransitionsByIdResponses, DeleteApiTasksByIdData, DeleteApiTasksByIdResponses, GetApiBoardsData, GetApiBoardsResponses, GetApiPhasesData, GetApiPhasesResponses, GetApiPhaseTransitionsData, GetApiPhaseTransitionsResponses, GetApiTasksData, GetApiTasksResponses, GetBoardData, GetBoardResponses, GetData, GetPhaseData, GetPhaseResponses, GetPhasesByBoardByIdData, GetPhasesByBoardByIdResponses, GetResponses, GetTaskData, GetTaskResponses, GetTransitionData, GetTransitionResponses, PostApiBoardsData, PostApiBoardsResponses, PostApiPhasesData, PostApiPhasesResponses, PostApiPhaseTransitionsData, PostApiPhaseTransitionsResponses, PostApiTasksData, PostApiTasksResponses, PutApiBoardsByIdData, PutApiBoardsByIdResponses, PutApiPhasesByIdData, PutApiPhasesByIdResponses, PutApiPhaseTransitionsByIdData, PutApiPhaseTransitionsByIdResponses, PutApiTasksByIdData, PutApiTasksByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiBoards = <ThrowOnError extends boolean = false>(options?: Options<GetApiBoardsData, ThrowOnError>) => (options?.client ?? client).get<GetApiBoardsResponses, unknown, ThrowOnError>({ url: '/api/Boards', ...options });

export const postApiBoards = <ThrowOnError extends boolean = false>(options?: Options<PostApiBoardsData, ThrowOnError>) => (options?.client ?? client).post<PostApiBoardsResponses, unknown, ThrowOnError>({
    url: '/api/Boards',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiBoardsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiBoardsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiBoardsByIdResponses, unknown, ThrowOnError>({ url: '/api/Boards/{id}', ...options });

export const getBoard = <ThrowOnError extends boolean = false>(options: Options<GetBoardData, ThrowOnError>) => (options.client ?? client).get<GetBoardResponses, unknown, ThrowOnError>({ url: '/api/Boards/{id}', ...options });

export const putApiBoardsById = <ThrowOnError extends boolean = false>(options: Options<PutApiBoardsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiBoardsByIdResponses, unknown, ThrowOnError>({
    url: '/api/Boards/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const getApiPhases = <ThrowOnError extends boolean = false>(options?: Options<GetApiPhasesData, ThrowOnError>) => (options?.client ?? client).get<GetApiPhasesResponses, unknown, ThrowOnError>({ url: '/api/Phases', ...options });

export const postApiPhases = <ThrowOnError extends boolean = false>(options?: Options<PostApiPhasesData, ThrowOnError>) => (options?.client ?? client).post<PostApiPhasesResponses, unknown, ThrowOnError>({
    url: '/api/Phases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiPhasesById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiPhasesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiPhasesByIdResponses, unknown, ThrowOnError>({ url: '/api/Phases/{id}', ...options });

export const getPhase = <ThrowOnError extends boolean = false>(options: Options<GetPhaseData, ThrowOnError>) => (options.client ?? client).get<GetPhaseResponses, unknown, ThrowOnError>({ url: '/api/Phases/{id}', ...options });

export const putApiPhasesById = <ThrowOnError extends boolean = false>(options: Options<PutApiPhasesByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiPhasesByIdResponses, unknown, ThrowOnError>({
    url: '/api/Phases/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getPhasesByBoardById = <ThrowOnError extends boolean = false>(options: Options<GetPhasesByBoardByIdData, ThrowOnError>) => (options.client ?? client).get<GetPhasesByBoardByIdResponses, unknown, ThrowOnError>({ url: '/phasesByBoard/{id}', ...options });

export const getApiPhaseTransitions = <ThrowOnError extends boolean = false>(options?: Options<GetApiPhaseTransitionsData, ThrowOnError>) => (options?.client ?? client).get<GetApiPhaseTransitionsResponses, unknown, ThrowOnError>({ url: '/api/PhaseTransitions', ...options });

export const postApiPhaseTransitions = <ThrowOnError extends boolean = false>(options?: Options<PostApiPhaseTransitionsData, ThrowOnError>) => (options?.client ?? client).post<PostApiPhaseTransitionsResponses, unknown, ThrowOnError>({
    url: '/api/PhaseTransitions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiPhaseTransitionsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiPhaseTransitionsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiPhaseTransitionsByIdResponses, unknown, ThrowOnError>({ url: '/api/PhaseTransitions/{id}', ...options });

export const getTransition = <ThrowOnError extends boolean = false>(options: Options<GetTransitionData, ThrowOnError>) => (options.client ?? client).get<GetTransitionResponses, unknown, ThrowOnError>({ url: '/api/PhaseTransitions/{id}', ...options });

export const putApiPhaseTransitionsById = <ThrowOnError extends boolean = false>(options: Options<PutApiPhaseTransitionsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiPhaseTransitionsByIdResponses, unknown, ThrowOnError>({
    url: '/api/PhaseTransitions/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiTasks = <ThrowOnError extends boolean = false>(options?: Options<GetApiTasksData, ThrowOnError>) => (options?.client ?? client).get<GetApiTasksResponses, unknown, ThrowOnError>({ url: '/api/Tasks', ...options });

export const postApiTasks = <ThrowOnError extends boolean = false>(options?: Options<PostApiTasksData, ThrowOnError>) => (options?.client ?? client).post<PostApiTasksResponses, unknown, ThrowOnError>({
    url: '/api/Tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiTasksById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTasksByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiTasksByIdResponses, unknown, ThrowOnError>({ url: '/api/Tasks/{id}', ...options });

export const getTask = <ThrowOnError extends boolean = false>(options: Options<GetTaskData, ThrowOnError>) => (options.client ?? client).get<GetTaskResponses, unknown, ThrowOnError>({ url: '/api/Tasks/{id}', ...options });

export const putApiTasksById = <ThrowOnError extends boolean = false>(options: Options<PutApiTasksByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiTasksByIdResponses, unknown, ThrowOnError>({
    url: '/api/Tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
