// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Board = {
    id?: number;
    name: string | null;
    phases?: Array<Phase> | null;
};

export type Phase = {
    id?: number;
    name: string | null;
    boardId?: number;
    phaseMovement?: Array<PhaseTransitions> | null;
    tasks?: Array<Task> | null;
};

export type PhaseTransitions = {
    id?: number;
    fromPhaseId?: number;
    fromPhase?: Phase;
    toPhaseId?: number;
    toPhase?: Phase;
};

export type Priority = 0 | 1 | 2 | 3 | 4;

export type Task = {
    id?: number;
    title: string;
    description?: string | null;
    phaseId?: number;
    phase?: Phase;
    priority?: Priority;
    storyPoints?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type GetApiBoardsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Boards';
};

export type GetApiBoardsResponses = {
    /**
     * OK
     */
    200: Array<Board>;
};

export type GetApiBoardsResponse = GetApiBoardsResponses[keyof GetApiBoardsResponses];

export type PostApiBoardsData = {
    body?: Board;
    path?: never;
    query?: never;
    url: '/api/Boards';
};

export type PostApiBoardsResponses = {
    /**
     * OK
     */
    200: Board;
};

export type PostApiBoardsResponse = PostApiBoardsResponses[keyof PostApiBoardsResponses];

export type DeleteApiBoardsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Boards/{id}';
};

export type DeleteApiBoardsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetBoardData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Boards/{id}';
};

export type GetBoardResponses = {
    /**
     * OK
     */
    200: Board;
};

export type GetBoardResponse = GetBoardResponses[keyof GetBoardResponses];

export type PutApiBoardsByIdData = {
    body?: Board;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Boards/{id}';
};

export type PutApiBoardsByIdResponses = {
    /**
     * OK
     */
    200: Board;
};

export type PutApiBoardsByIdResponse = PutApiBoardsByIdResponses[keyof PutApiBoardsByIdResponses];

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetApiPhasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Phases';
};

export type GetApiPhasesResponses = {
    /**
     * OK
     */
    200: Array<Phase>;
};

export type GetApiPhasesResponse = GetApiPhasesResponses[keyof GetApiPhasesResponses];

export type PostApiPhasesData = {
    body?: Phase;
    path?: never;
    query?: never;
    url: '/api/Phases';
};

export type PostApiPhasesResponses = {
    /**
     * OK
     */
    200: Phase;
};

export type PostApiPhasesResponse = PostApiPhasesResponses[keyof PostApiPhasesResponses];

export type DeleteApiPhasesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Phases/{id}';
};

export type DeleteApiPhasesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPhaseData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Phases/{id}';
};

export type GetPhaseResponses = {
    /**
     * OK
     */
    200: Phase;
};

export type GetPhaseResponse = GetPhaseResponses[keyof GetPhaseResponses];

export type PutApiPhasesByIdData = {
    body?: Phase;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Phases/{id}';
};

export type PutApiPhasesByIdResponses = {
    /**
     * OK
     */
    200: Phase;
};

export type PutApiPhasesByIdResponse = PutApiPhasesByIdResponses[keyof PutApiPhasesByIdResponses];

export type GetPhasesByBoardByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        includeTask?: boolean;
    };
    url: '/phasesByBoard/{id}';
};

export type GetPhasesByBoardByIdResponses = {
    /**
     * OK
     */
    200: Array<Phase>;
};

export type GetPhasesByBoardByIdResponse = GetPhasesByBoardByIdResponses[keyof GetPhasesByBoardByIdResponses];

export type GetApiPhaseTransitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PhaseTransitions';
};

export type GetApiPhaseTransitionsResponses = {
    /**
     * OK
     */
    200: Array<PhaseTransitions>;
};

export type GetApiPhaseTransitionsResponse = GetApiPhaseTransitionsResponses[keyof GetApiPhaseTransitionsResponses];

export type PostApiPhaseTransitionsData = {
    body?: PhaseTransitions;
    path?: never;
    query?: never;
    url: '/api/PhaseTransitions';
};

export type PostApiPhaseTransitionsResponses = {
    /**
     * OK
     */
    200: PhaseTransitions;
};

export type PostApiPhaseTransitionsResponse = PostApiPhaseTransitionsResponses[keyof PostApiPhaseTransitionsResponses];

export type DeleteApiPhaseTransitionsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/PhaseTransitions/{id}';
};

export type DeleteApiPhaseTransitionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTransitionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/PhaseTransitions/{id}';
};

export type GetTransitionResponses = {
    /**
     * OK
     */
    200: PhaseTransitions;
};

export type GetTransitionResponse = GetTransitionResponses[keyof GetTransitionResponses];

export type PutApiPhaseTransitionsByIdData = {
    body?: PhaseTransitions;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/PhaseTransitions/{id}';
};

export type PutApiPhaseTransitionsByIdResponses = {
    /**
     * OK
     */
    200: PhaseTransitions;
};

export type PutApiPhaseTransitionsByIdResponse = PutApiPhaseTransitionsByIdResponses[keyof PutApiPhaseTransitionsByIdResponses];

export type GetApiTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Tasks';
};

export type GetApiTasksResponses = {
    /**
     * OK
     */
    200: Array<Task>;
};

export type GetApiTasksResponse = GetApiTasksResponses[keyof GetApiTasksResponses];

export type PostApiTasksData = {
    body?: Task;
    path?: never;
    query?: never;
    url: '/api/Tasks';
};

export type PostApiTasksResponses = {
    /**
     * OK
     */
    200: Task;
};

export type PostApiTasksResponse = PostApiTasksResponses[keyof PostApiTasksResponses];

export type DeleteApiTasksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Tasks/{id}';
};

export type DeleteApiTasksByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Tasks/{id}';
};

export type GetTaskResponses = {
    /**
     * OK
     */
    200: Task;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type PutApiTasksByIdData = {
    body?: Task;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/Tasks/{id}';
};

export type PutApiTasksByIdResponses = {
    /**
     * OK
     */
    200: Task;
};

export type PutApiTasksByIdResponse = PutApiTasksByIdResponses[keyof PutApiTasksByIdResponses];
